name: Setup deno
description: Sets up deno and installs dependencies
inputs:
  version:
    description: The version of deno to install
    required: false
    default: v1.x
  entrypoint:
    description: The TypeScript entrypoint path
    required: false
    default: ./mod.ts
  cache-lock:
    description: The cache lockfile to use
    required: false
    default: lock.json

runs:
  using: composite
  steps:
    - name: setup deno
      id: setup
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ inputs.version }}

    - name: cache deno dependencies
      uses: actions/cache@v2
      with:
        key: |
          ${{ runner.os }}-deno-${{ steps.setup.outputs.deno-version }}-${{ hashFiles('**/*.ts') }}
        restore-keys: |
          ${{ runner.os }}-deno-${{ steps.setup.outputs.deno-version }}-
          ${{ runner.os }}-deno-
        path: |
          ${{ inputs.cache-path }}/deps/https

    - name: fetch any uncached dependencies
      shell: bash
      run: |
        deno cache --reload=file: ${{ inputs.entrypoint }}

    - name: check lockfile
      shell: bash
      run: |
        if [[ -f ${{ inputs.cache-lock }} ]]; then
          deno cache --lock=${{ inputs.cache-lock }} --cached-only ${{ inputs.entrypoint }}
        fi
        deno cache --lock-write --lock=${{ inputs.cache-lock }} ${{ inputs.entrypoint }}
        echo >> ${{ inputs.cache-lock }}
